# PDF directories to load
PDF_DIRS:
  - ./documents/free
  #- ./documents/purchased

# Text splitting
text_splitter:
  chunk_size: 2000
  chunk_overlap: 200
  separators:
    - "\n\n"
    - "\n"
    - " "
    - "."

# PGVector
vectorstore:
  collection_name: documents
  search_kwargs:
    k: 1 # how many documents to retrieve

# LLM defaults
llm:
  model:  mistral-7b-instruct-v0.1.Q5_K_M 
  temperature: 0
  chain_type: stuff
embeddings:
  model: nomic-embed-text-v1.5
