"""Defines the state structure for the RAG agent.
This is essentially to know what keys are expected to be in the state
dictionary passed around the graph nodes.

TODO: as an exercise, we could add more states, as for example InputState, OutputState, etc.
"""
from typing import TypedDict
from langchain_core.documents import Document

class AgentState(TypedDict):
    """
    All the possible state keys used by the RAG agent and that
    can be updated (created, read, edited) by the various nodes.
    
    Attributes:
        question: The user's original question.
        documents: List of retrieved documents.
        generation: The final answer generated by the LLM.
        search_failed: Binary flag ('YES'/'NO') if retrieval found nothing.
        retry_count: Loop counter to prevent infinite loops.
    """
    question: str
    documents: list[Document]
    generation: str
    search_failed: str 
    retry_count: int