services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container-lg
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6025:5432"
    volumes:
      - ./pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
