# PDF directories to load
pdf:
  paths:
    - ./documents/stellantis
  loader: pypdfium2 # or pdfplumber
  read_mode:  single # page or single
  delim: "\n----CUSTOM_END----\n" # for single whe should put something like "\n----CUSTOM_END----\n"
  chunk_strategy: toc # recursive, qa, semantic, 

# Text splitting
text_splitter:
  chunk_size: 1000
  chunk_overlap: 100
  separators:
    - "\n\n"
    - "\n"
    - " "
    - "."
    
# Vector Store Settings
vectorstore:
  type: pgvector  # Options: pgvector, qdrant
  collection_name: documents
  search_kwargs:
    k: 2

# Semantic Caching (Redis)
semantic_caching:
  enabled: True
  threshold: 0.9

# LLM defaults
llm:
  model:  Meta-Llama-3.1-8B-Instruct-Q5_K_M
  temperature: 0
  chain_type: stuff
embeddings:
  model: all-MiniLM-L6-v2-ggml-model-f16

# Ragas evaluation settings
evaluation:
  test_file_path: test_dataset.csv
  judge_llm:
    model: Meta-Llama-3.1-8B-Instruct-Q5_K_M

# Services control
services:
  llamacpp:
    start: True
    stop: False
  pgvector:
    start: True
    stop: False
  redis:
    start: True
    stop: False
  qdrant:
    start: True
    stop: False
  langfuse:
    start: True
    stop: False
  mlflow:
    start: True
    stop: False
    experiment_name: "rag_mlflow_with_dataset2"
  litellm:
    start: False
    stop: False
  stop_all: False