model_list:
  - model_name: Meta-Llama-3.1-8B-Instruct-Q5_K_M
    litellm_params:
      model: openai/Meta-Llama-3.1-8B-Instruct-Q5_K_M
      api_key: "ignored"
      api_base: http://localhost:8080/v1